### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by 1300371** [LuckyEddie47/kstars_extensions#3]
Is it possible to provide Windows binaries ?

Unfortunately, i use kstarts on Windows 😅 

Regards,

**Comment by 1300371** [comment]
To be honest, i'm not comfortable with cpp.

I tried to compile on my own but i faced issues regarding QT ...
```
CMake Error at CMakeLists.txt:12 (find_package):
  Could not find a package configuration file provided by "QT" with any of
  the following names:

    Qt6Config.cmake
    qt6-config.cmake
    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "QT" to CMAKE_PREFIX_PATH or set "QT_DIR" to
  a directory containing one of the above files.  If "QT" provides a separate
  development package or SDK, be sure it has been installed.
```

**Comment by LuckyEddie47** [comment]
Theoretically I could build Windows binaries, if I borrow time on a Windows PC, but I suspect the result won't be very useful. 

The main issue is that KStars/Ekos use an IPC system called DBus for external communications. DBus is not that well supported on Windows. There is at least one implementation but you'd have to research and configure that yourself. 

If DBus works then the extension system could be used but some of the extensions definitely won't work on Windows anyway. The KStars backup extension needs some Posix system commands (tar, df & du) to function and the Siril EAA extension needs named pipes to talk to Siril. As far as I'm aware none of this is available in Windows. 

It might be worth exploring if WSL is a way forward for you.

**Comment by 1300371** [comment]
Meh ... Windows ... 
Thanks for the explanation 👍
